// src/components/countryCodeMap.js

const countryCodeMap = {
  "USA": "US",
  "Canada": "CA",
  "France": "FR",
  "Spain": "ES",
  "Germany": "DE",
  "Australia": "AU",
  "Nigeria": "NG",
  "Senegal": "SN",
  "Cameroon": "CM",
  "Greece": "GR",
  "Serbia": "RS",
  "Croatia": "HR",
  "Lithuania": "LT",
  "Slovenia": "SI",
  "Latvia": "LV",
  "Turkey": "TR",
  "Italy": "IT",
  "Brazil": "BR",
  "Argentina": "AR",
  "Dominican Republic": "DO",
  "Puerto Rico": "PR",
  "Bahamas": "BS",
  "Congo": "CD",
  "South Sudan": "SS",
  "Ukraine": "UA",
  "Georgia": "GE",
  "Israel": "IL",
  "Japan": "JP",
  "China": "CN",
  "Montenegro": "ME",
  "Switzerland": "CH",
  "New Zealand": "NZ",
  "Mexico": "MX",
  "Mali": "ML",
  "Bosnia and Herzegovina": "BA",
  "Finland": "FI",
  "Sudan": "SD",
  "United Kingdom": "GB",
  "Austria": "AT",
  "Egypt": "EG",
  "Poland": "PL",
  "Venezuela": "VE",
  "Czech Republic": "CZ",
  "Republic of the Congo": "CG"
};

export default countryCodeMap;
