// teamJerseyMap.js
const teamJerseyMap = {
  Raptors:       { svg: 'raptors.svg',       numberColor: '#BE0F34', jerseyColor: 'black' },
  Celtics:       { svg: 'celtics.svg',       numberColor: 'white',  jerseyColor: '#008853' },
  Nets:          { svg: 'nets.svg',          numberColor: 'white',  jerseyColor: 'black' },
  Knicks:        { svg: 'knicks.svg',        numberColor: '#F48328', jerseyColor: '#046AB4' },
  Sixers:        { svg: '76ers.svg',         numberColor: 'white',  jerseyColor: '#003DA5' },
  Bulls:         { svg: 'bulls.svg',         numberColor: 'black',  jerseyColor: '#BC032B' },
  Cavaliers:     { svg: 'cavaliers.svg',     numberColor: '#fbdd30', jerseyColor: '#860038' },
  Pistons:       { svg: 'pistons.svg',       numberColor: '#ED174C', jerseyColor: '#002D62' },
  Pacers:        { svg: 'pacers.svg',        numberColor: '#FFC526', jerseyColor: '#002D62' },
  Bucks:         { svg: 'bucks.svg',         numberColor: '#EFEBD2', jerseyColor: '#00461B' },
  Hawks:         { svg: 'hawks.svg',         numberColor: '#FDB927', jerseyColor: '#C8102E' },
  Hornets:       { svg: 'hornets.svg',       numberColor: '#1D0C65', jerseyColor: '#1D8CAB' },
  Heat:          { svg: 'heat.svg',          numberColor: '#38B4C8', jerseyColor: 'black' },
  Magic:         { svg: 'magic.svg',         numberColor: 'white',  jerseyColor: '#0478BE' },
  Wizards:       { svg: 'wizards.svg',       numberColor: 'white',  jerseyColor: '#E51837' },
  Nuggets:       { svg: 'nuggets.svg',       numberColor: '#FEC525', jerseyColor: '#0D2440' },
  Timberwolves:  { svg: 'timberwolves.svg',  numberColor: '#1E6194', jerseyColor: '#041D3E' },
  Thunder:       { svg: 'thunder.svg',       numberColor: 'white',  jerseyColor: '#007AC3' },
  Trailblazers:  { svg: 'trailblazers.svg',  numberColor: 'white',  jerseyColor: 'black' },
  Jazz:          { svg: 'jazz.svg',          numberColor: 'white',  jerseyColor: '#31006F' },
  Warriors:      { svg: 'warriors.svg',      numberColor: '#FDB927', jerseyColor: '#006BB6' },
  Clippers:      { svg: 'clippers.svg',      numberColor: 'white',  jerseyColor: '#0061A1' },
  Lakers:        { svg: 'lakers.svg',        numberColor: '#542583', jerseyColor: '#FDB827' },
  Suns:          { svg: 'suns.svg',          numberColor: '#E66226', jerseyColor: '#27235C' },
  Kings:         { svg: 'kings.svg',         numberColor: 'white',  jerseyColor: 'black' },
  Mavericks:     { svg: 'mavericks.svg',     numberColor: '#C4CED4', jerseyColor: '#1061AC' },
  Rockets:       { svg: 'rockets.svg',       numberColor: 'white',  jerseyColor: '#D31145' },
  Grizzlies:     { svg: 'grizzlies.svg',     numberColor: '#6189B9', jerseyColor: '#23375B' },
  Pelicans:      { svg: 'pelicans.svg',      numberColor: 'white',  jerseyColor: '#002A5C' },
  Spurs:         { svg: 'spurs.svg',         numberColor: '#84888B', jerseyColor: 'black' },
};

export default teamJerseyMap;
