// teamJerseyMap.js
const teamJerseyMap = {
  Raptors:       { svg: 'raptors.svg',       numberColor: '#BE0F34' },
  Celtics:       { svg: 'celtics.svg',       numberColor: 'white'  },
  Nets:          { svg: 'nets.svg',          numberColor: 'white'  },
  Knicks:        { svg: 'knicks.svg',        numberColor: '#F48328' },
  Sixers:        { svg: '76ers.svg',         numberColor: 'white'  },
  Bulls:         { svg: 'bulls.svg',         numberColor: 'black'  },
  Cavaliers:     { svg: 'cavaliers.svg',     numberColor: '#fbdd30' },
  Pistons:       { svg: 'pistons.svg',       numberColor: '#ED174C' },
  Pacers:        { svg: 'pacers.svg',        numberColor: '#FFC526' },
  Bucks:         { svg: 'bucks.svg',         numberColor: '#EFEBD2' },
  Hawks:         { svg: 'hawks.svg',         numberColor: '#FDB927' },
  Hornets:       { svg: 'hornets.svg',       numberColor: '#1D0C65' },
  Heat:          { svg: 'heat.svg',          numberColor: '#38B4C8' },
  Magic:         { svg: 'magic.svg',         numberColor: 'white'  },
  Wizards:       { svg: 'wizards.svg',       numberColor: 'white'  },
  Nuggets:       { svg: 'nuggets.svg',       numberColor: '#FEC525' },
  Timberwolves:  { svg: 'timberwolves.svg',  numberColor: '#1E6194' },
  Thunder:       { svg: 'thunder.svg',       numberColor: 'white'  },
  Trailblazers:  { svg: 'trailblazers.svg',  numberColor: 'white'  },
  Jazz:          { svg: 'jazz.svg',          numberColor: 'white'  },
  Warriors:      { svg: 'warriors.svg',      numberColor: '#FDB927' },
  Clippers:      { svg: 'clippers.svg',      numberColor: 'white'  },
  Lakers:        { svg: 'lakers.svg',        numberColor: '#542583' },
  Suns:          { svg: 'suns.svg',          numberColor: '#E66226' },
  Kings:         { svg: 'kings.svg',         numberColor: 'white'  },
  Mavericks:     { svg: 'mavericks.svg',     numberColor: '#C4CED4' },
  Rockets:       { svg: 'rockets.svg',       numberColor: 'white'  },
  Grizzlies:     { svg: 'grizzlies.svg',     numberColor: '#6189B9' },
  Pelicans:      { svg: 'pelicans.svg',      numberColor: 'white'  },
  Spurs:         { svg: 'spurs.svg',         numberColor: '#84888B' },
};

export default teamJerseyMap;
